<project>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.chattoorder</groupId>
        <artifactId>chat-pos-backend</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>chat-pos-domain</artifactId>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>