<project>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.chattoorder</groupId>
        <artifactId>chat-pos-backend</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>chat-pos-boot</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <!-- Your project -->
        <dependency>
            <groupId>com.chattoorder</groupId>
            <artifactId>chat-pos-infrastructure</artifactId>
        </dependency>

        <!-- API Layer -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- WebClient -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>